# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PacketAssistant\attach.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttachWindow(object):
    def setupUi(self, AttachWindow):
        AttachWindow.setObjectName("AttachWindow")
        AttachWindow.resize(334, 115)
        self.centralwidget = QtWidgets.QWidget(AttachWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 40, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.label.setMinimumSize(QtCore.QSize(61, 0))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 40, 61, 31))
        self.lineEdit.setObjectName("lineEdit")
        AttachWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AttachWindow)
        self.statusbar.setObjectName("statusbar")
        AttachWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AttachWindow)
        QtCore.QMetaObject.connectSlotsByName(AttachWindow)

    def retranslateUi(self, AttachWindow):
        _translate = QtCore.QCoreApplication.translate
        AttachWindow.setWindowTitle(_translate("AttachWindow", "进程注入"))
        self.pushButton.setText(_translate("AttachWindow", "注入"))
        self.label.setText(_translate("AttachWindow", "进程PID:"))
        self.lineEdit.setText(_translate("AttachWindow", "11804"))
